export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const LOCALE_SET = "LOCALE_SET";
export const ERROR_MSG_RESET = "ERROR_MSG_RESET";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const CONFIRM_USER_REQUEST = "CONFIRM_USER_REQUEST";
export const CONFIRM_USER_FAILURE = "CONFIRM_USER_FAILURE";

export const FETCH_CURRENT_USER_REQUEST = "FETCH_CURRENT_USER_REQUEST";
export const FETCH_CURRENT_USER_SUCCESS = "FETCH_CURRENT_USER_SUCCESS";
export const FETCH_CURRENT_USER_FAILURE = "FETCH_CURRENT_USER_FAILURE";

export const USER_AVATAR_UPLOAD_REQUEST = "USER_AVATAR_UPLOAD_REQUEST";
export const USER_AVATAR_UPLOAD_SUCCESS = "USER_AVATAR_UPLOAD_SUCCESS";
export const USER_AVATAR_UPLOAD_FAILURE = "USER_AVATAR_UPLOAD_FAILURE";

export const UPDATE_AUTH_USER_EMAIL_REQUEST = "UPDATE_AUTH_USER_EMAIL_REQUEST";
export const UPDATE_AUTH_USER_EMAIL_SUCCESS = "UPDATE_AUTH_USER_EMAIL_SUCCESS";
export const UPDATE_AUTH_USER_EMAIL_FAILURE = "UPDATE_AUTH_USER_EMAIL_FAILURE";

export const UPDATE_AUTH_USER_PASSWORD_REQUEST = "UPDATE_AUTH_USER_PASSWORD_REQUEST";
export const UPDATE_AUTH_USER_PASSWORD_SUCCESS = "UPDATE_AUTH_USER_PASSWORD_SUCCESS";
export const UPDATE_AUTH_USER_PASSWORD_FAILURE = "UPDATE_AUTH_USER_PASSWORD_FAILURE";

export const UPDATE_AUTH_USER_PROFILE_REQUEST = "UPDATE_AUTH_USER_PROFILE_REQUEST";
export const UPDATE_AUTH_USER_PROFILE_SUCCESS = "UPDATE_AUTH_USER_PROFILE_SUCCESS";
export const UPDATE_AUTH_USER_PROFILE_FAILURE = "UPDATE_AUTH_USER_PROFILE_FAILURE";
