export const ADD_BLOG_REQUEST = "ADD_BLOG_REQUEST";
export const ADD_BLOG_SUCCESS = "ADD_BLOG_SUCCESS";
export const ADD_BLOG_FAILURE = "ADD_BLOG_FAILURE";

export const FETCH_ALL_BLOG_REQUEST = "FETCH_ALL_BLOG_REQUEST";
export const FETCH_ALL_BLOG_SUCCESS = "FETCH_ALL_BLOG_SUCCESS";
export const FETCH_ALL_BLOG_FAILURE = "FETCH_ALL_BLOG_FAILURE";

export const UPDATE_BLOG_REQUEST = "UPDATE_BLOG_REQUEST";
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS";
export const UPDATE_BLOG_FAILURE = "UPDATE_BLOG_FAILURE";

export const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST";
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";
export const DELETE_BLOG_FAILURE = "DELETE_BLOG_FAILURE";

export const ACTIVATE_BLOG_REQUEST = "ACTIVATE_BLOG_REQUEST";
export const ACTIVATE_BLOG_SUCCESS = "ACTIVATE_BLOG_SUCCESS";
export const ACTIVATE_BLOG_FAILURE = "ACTIVATE_BLOG_FAILURE";