export const ADD_EXPERIENCE_REQUEST = "ADD_EXPERIENCE_REQUEST";
export const ADD_EXPERIENCE_SUCCESS = "ADD_EXPERIENCE_SUCCESS";
export const ADD_EXPERIENCE_FAILURE = "ADD_EXPERIENCE_FAILURE";
export const FETCH_ALL_EXPERIENCE_REQUEST = "FETCH_ALL_EXPERIENCE_REQUEST";
export const FETCH_ALL_EXPERIENCE_SUCCESS = "FETCH_ALL_EXPERIENCE_SUCCESS";
export const FETCH_ALL_EXPERIENCE_FAILURE = "FETCH_ALL_EXPERIENCE_FAILURE";
export const UPDATE_EXPERIENCE_REQUEST = "UPDATE_EXPERIENCE_REQUEST";
export const UPDATE_EXPERIENCE_SUCCESS = "UPDATE_EXPERIENCE_SUCCESS";
export const UPDATE_EXPERIENCE_FAILURE = "UPDATE_EXPERIENCE_FAILURE";
export const DELETE_EXPERIENCE_REQUEST = "DELETE_EXPERIENCE_REQUEST";
export const DELETE_EXPERIENCE_SUCCESS = "DELETE_EXPERIENCE_SUCCESS";
export const DELETE_EXPERIENCE_FAILURE = "DELETE_EXPERIENCE_FAILURE";
export const FETCH_SINGLE_EXPERIENCE_REQUEST = "FETCH_SINGLE_EXPERIENCE_REQUEST";
export const FETCH_SINGLE_EXPERIENCE_SUCCESS = "FETCH_SINGLE_EXPERIENCE_SUCCESS";
export const FETCH_SINGLE_EXPERIENCE_FAILURE = "FETCH_SINGLE_EXPERIENCE_FAILURE";

export const CHANGE_CURRENT_EXPERIENCE_REQUEST = "CHANGE_CURRENT_EXPERIENCE_REQUEST";
export const CHANGE_CURRENT_EXPERIENCE_SUCCESS = "CHANGE_CURRENT_EXPERIENCE_SUCCESS";
export const CHANGE_CURRENT_EXPERIENCE_FAILURE = "CHANGE_CURRENT_EXPERIENCE_FAILURE";

export const CHANGE_STATUS_EXPERIENCE_REQUEST = "CHANGE_STATUS_EXPERIENCE_REQUEST";
export const CHANGE_STATUS_EXPERIENCE_SUCCESS = "CHANGE_STATUS_EXPERIENCE_SUCCESS";
export const CHANGE_STATUS_EXPERIENCE_FAILURE = "CHANGE_STATUS_EXPERIENCE_FAILURE";
