export const ADD_PORTFOLIO_REQUEST = "ADD_PORTFOLIO_REQUEST";
export const ADD_PORTFOLIO_SUCCESS = "ADD_PORTFOLIO_SUCCESS";
export const ADD_PORTFOLIO_FAILURE = "ADD_PORTFOLIO_FAILURE";

export const FETCH_ALL_PORTFOLIO_REQUEST = "FETCH_ALL_PORTFOLIO_REQUEST";
export const FETCH_ALL_PORTFOLIO_SUCCESS = "FETCH_ALL_PORTFOLIO_SUCCESS";
export const FETCH_ALL_PORTFOLIO_FAILURE = "FETCH_ALL_PORTFOLIO_FAILURE";

export const UPDATE_PORTFOLIO_REQUEST = "UPDATE_PORTFOLIO_REQUEST";
export const UPDATE_PORTFOLIO_SUCCESS = "UPDATE_PORTFOLIO_SUCCESS";
export const UPDATE_PORTFOLIO_FAILURE = "UPDATE_PORTFOLIO_FAILURE";

export const DELETE_PORTFOLIO_REQUEST = "DELETE_PORTFOLIO_REQUEST";
export const DELETE_PORTFOLIO_SUCCESS = "DELETE_PORTFOLIO_SUCCESS";
export const DELETE_PORTFOLIO_FAILURE = "DELETE_PORTFOLIO_FAILURE";

export const FETCH_SINGLE_PORTFOLIO_REQUEST = "FETCH_SINGLE_PORTFOLIO_REQUEST";
export const FETCH_SINGLE_PORTFOLIO_SUCCESS = "FETCH_SINGLE_PORTFOLIO_SUCCESS";
export const FETCH_SINGLE_PORTFOLIO_FAILURE = "FETCH_SINGLE_PORTFOLIO_FAILURE";

export const ACTIVATE_PORTFOLIO_REQUEST = "ACTIVATE_PORTFOLIO_REQUEST";
export const ACTIVATE_PORTFOLIO_SUCCESS = "ACTIVATE_PORTFOLIO_SUCCESS";
export const ACTIVATE_PORTFOLIO_FAILURE = "ACTIVATE_PORTFOLIO_FAILURE";