export const ADD_EDUCATION_REQUEST = "ADD_EDUCATION_REQUEST";
export const ADD_EDUCATION_SUCCESS = "ADD_EDUCATION_SUCCESS";
export const ADD_EDUCATION_FAILURE = "ADD_EDUCATION_FAILURE";
export const FETCH_ALL_EDUCATION_REQUEST = "FETCH_ALL_EDUCATION_REQUEST";
export const FETCH_ALL_EDUCATION_SUCCESS = "FETCH_ALL_EDUCATION_SUCCESS";
export const FETCH_ALL_EDUCATION_FAILURE = "FETCH_ALL_EDUCATION_FAILURE";
export const UPDATE_EDUCATION_REQUEST = "UPDATE_EDUCATION_REQUEST";
export const UPDATE_EDUCATION_SUCCESS = "UPDATE_EDUCATION_SUCCESS";
export const UPDATE_EDUCATION_FAILURE = "UPDATE_EDUCATION_FAILURE";
export const DELETE_EDUCATION_REQUEST = "DELETE_EDUCATION_REQUEST";
export const DELETE_EDUCATION_SUCCESS = "DELETE_EDUCATION_SUCCESS";
export const DELETE_EDUCATION_FAILURE = "DELETE_EXPERIENCE_FAILURE";

export const ACTIVATE_EDUCATION_REQUEST = "ACTIVATE_EDUCATION_REQUEST";
export const ACTIVATE_EDUCATION_SUCCESS = "ACTIVATE_EDUCATION_SUCCESS";
export const ACTIVATE_EDUCATION_FAILURE = "ACTIVATE_EDUCATION_FAILURE";