export const ADD_STACK_REQUEST = "ADD_STACK_REQUEST";
export const ADD_STACK_SUCCESS = "ADD_STACK_SUCCESS";
export const ADD_STACK_FAILURE = "ADD_STACK_FAILURE";
export const FETCH_ALL_STACK_REQUEST = "FETCH_ALL_STACK_REQUEST";
export const FETCH_ALL_STACK_SUCCESS = "FETCH_ALL_STACK_SUCCESS";
export const FETCH_ALL_STACK_FAILURE = "FETCH_ALL_STACK_FAILURE";
export const UPDATE_STACK_REQUEST = "UPDATE_STACK_REQUEST";
export const UPDATE_STACK_SUCCESS = "UPDATE_STACK_SUCCESS";
export const UPDATE_STACK_FAILURE = "UPDATE_STACK_FAILURE";
export const DELETE_STACK_REQUEST = "DELETE_STACK_REQUEST";
export const DELETE_STACK_SUCCESS = "DELETE_STACK_SUCCESS";
export const DELETE_STACK_FAILURE = "DELETE_STACK_FAILURE";
export const FETCH_SINGLE_STACK_REQUEST = "FETCH_SINGLE_STACK_REQUEST";
export const FETCH_SINGLE_STACK_SUCCESS = "FETCH_SINGLE_STACK_SUCCESS";
export const FETCH_SINGLE_STACK_FAILURE = "FETCH_SINGLE_STACK_FAILURE";


export const ACTIVATE_STACK_REQUEST = "ACTIVATE_STACK_REQUEST";
export const ACTIVATE_STACK_SUCCESS = "ACTIVATE_STACK_SUCCESS";
export const ACTIVATE_STACK_FAILURE = "ACTIVATE_STACK_FAILURE";
